name: Sourcegraph Dart LSIF Indexer
description: Generate LSIF data from Dart source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  project_root: 
    description: The project root.
    default: .

runs:
  using: docker
  image: Dockerfile
  env:
    PROJECT_ROOT: ${{ inputs.project_root }}
