name: Sourcegraph Go LSIF Indexer
description: Generate LSIF data from Go source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  file:
    description: The output filename.
    default: .
  project_root: 
    description: The project root.
    default: .

runs:
  using: docker
  image: Dockerfile
  env:
    OUT: ${{ inputs.file }}
    PROJECT_ROOT: ${{ inputs.project_root }}
