name: Sourcegraph Dart LSIF Indexer
description: Generate LSIF data from Dart source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  file:
    description: The output filename (relative to the repository root).
    default: dump.lsif
  project_root:
    description: The project root (where crossdart is invoked).
    default: .

runs:
  using: docker
  image: Dockerfile
  env:
    OUT: ${{ inputs.file }}
    PROJECT_ROOT: ${{ inputs.project_root }}
